In [1]:
import numpy as np

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a.shape

(10,)

In [5]:
type(a)

numpy.ndarray

In [6]:
type(a.shape)

tuple

In [7]:
b = np.ones((3,4), dtype=int)

In [8]:
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
len(b.shape)

2

In [12]:
b.shape[0] #number or rows

3

In [13]:
b.shape[1] #number or columns

4

In [14]:
b.shape

(3, 4)

In [15]:
b.sum()

12

In [16]:
b.sum(axis=0)

array([3, 3, 3, 3])

In [17]:
b.sum(axis=0).ndim

1

In [19]:
b.sum(axis=0).size

4

In [20]:
b.sum(axis=1)

array([4, 4, 4])

In [25]:
N =5
m = np.zeros((N,N), dtype=int)
for i in range(N):
    m[i,i] = 1
    m[i, N-1-i] =1
m

array([[1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1]])

In [34]:
k = np.eye((N), dtype=int)
k

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [35]:
k[::-1, :]

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])