# Lab notebook - week 2

### * A note about cell output - expressions vs. statements

In [1]:
# Some code fragments produce output, see the red "Out[?]" below - such fragments are called expressions.
5 + 2

7

In [2]:
# Other fragments produce no output. Such fragments are called statements. Not that there is no "Out[]" below this cell.
x = 5 + 2

In [3]:
# If you want to see the value of x, just write x on another line, "x" is an "expression" and produces the value of x as output
y = 3 + 7
y

10

In [4]:
# A cell only produces one output - that of the last expression in the cell
x  # value of x is not shown
y 

10

In [5]:
# If you want to see several values, output them from different cells or use print()
# note that print() produces text, but it is not labeled as Out[] (why?)
print(x)
print(y)

7
10


## NumPy basics
Python lists are somewhat weird creatures. In contrast to basic array types in other languages like C# and Java, they can hold objects of different types and new elements can be inserted in the middle. NumPy arrays are much more like C# arrays - all elements have the same type.

In [6]:
# by convention numpy is always imported as np
import numpy as np

### Common ways of creating numpy arrays

In [7]:
a = np.array([5, 2, 17])  # Convert a Python list into a numpy array
a

array([ 5,  2, 17])

In [8]:
# List of lists gets converted into a 2D array
np.array([[5, 7, 2],
          [9, 4, 1]])


array([[5, 7, 2],
       [9, 4, 1]])

In [9]:
np.arange(5)  # Same as Python's range() but creates a numpy array

array([0, 1, 2, 3, 4])

In [10]:
np.zeros(5)  # Create a numpy array with five elements, all set to zero

array([0., 0., 0., 0., 0.])

In [11]:
c = np.ones(7)  # Create a numpy array with five elements, all set to 1
c


array([1., 1., 1., 1., 1., 1., 1.])

In [12]:
# Array of 6 random numbers between 0 and 1
np.random.rand(6)

array([0.46914111, 0.51000463, 0.36450447, 0.41292561, 0.44241854,
       0.43901642])

In [13]:
# array with 6 random integers between 0 and 100 (not including 100 as usual)
np.random.randint(100, size=6)

array([38, 28, 30, 30, 80, 80])

### Array properties

In [14]:
b = np.array([[5, 7, 2],
              [9, 4, 1]])
b

array([[5, 7, 2],
       [9, 4, 1]])

In [15]:
# The total number of elements
b.size 

6

In [16]:
# number of dimensions
b.ndim 

2

In [17]:
# array shape is a Python tuple, in this case it's (2, 3) because b is a 2 by 3 array.
b.shape

(2, 3)

In [18]:
# Data type of the array
a.dtype

dtype('int32')

In [19]:
# Note that zeros byt default uses the float64 data type
z = np.zeros(7)
z.dtype

dtype('float64')

In [20]:
# But data type can be set explicitly, almost all numpy functions that create arrays take an optional dtype parameter
# Let's set it to an 8 bit integer
z = np.zeros(7, dtype=np.int8)  
z.dtype

dtype('int8')

## Exercises

Read section 2.2 of the book (The Basics of NumPy Arrays) and complete the tasks below.


#### Convert a list into a numpy array

In [21]:
lst = [5, 3, 8, 4]
lst

[5, 3, 8, 4]

In [22]:
# your code here
x = 
x

SyntaxError: invalid syntax (<ipython-input-22-bb055f7d2cd9>, line 2)

#### What happens when you multiply a list by 3, what a about an array multiplied by 3?

In [ ]:
# Feel free to add more cells


#### Create an array of 10 ones

#### Create an array of 10 fives

#### Create an array of the integers from 10 to 50 (including 50)

#### Create an array of 10 random numbers between 0 and 5 (not integers)

#### Read the help for np.linspace function and create an array of 11 evenly spaced elements between 0 and 2

#### Create a 3 by 4 array of ones

#### Create a 3 by 4 array of fives

#### Create a 3x3 matrix with values ranging from 0 to 8 (use reshape)

## Element selection
Using the following arrays `a` and `m`

In [ ]:
a = np.arange(10,21)
a

In [ ]:
m = np.arange(1,22).reshape((3,7))
m

### Create an array containing... 
#### the first 4 elements of a

#### the last 3 elements of a

#### The middle elements of a from 15 to 18 inclusive

#### The first column of m

#### The middle row of m

#### The left 3 columns of m

#### The bottom-right 2 by 2 square

#### (bonus) every other element of a  

#### Subtract 5 from each element of a

#### Create an array containing squares of all numbers from 1 to 10 (inclusive)

#### Create an array containing all powers of 2 from $2^0$ to $2^{10}$ (inclusive)

#### Same as above (powers of two), but subtract one from each element, that is $a_k = 2^k - 1$

### Bonus task
Write code that lists all available dtypes with specified number of bits 

In [ ]:
# Hint
np.int8